version: '3'
services:
  #  nginx:
  #      image: nginx:latest
  #      container_name: express_mongo_proxy_1
  #      volumes:
  #        - ./config/nginx.conf:/etc/nginx/nginx.conf
  ##        - ./nginx/log:/var/log/nginx/
  ##        - ./nginx/cache/:/etc/nginx/cache
  #      ports:
  #        - 80:80
  #        - 443:443
  ##      networks:
  ##        - express-mongo-network
  #      depends_on:
  #        - api
  #      links:
  #        - api

  db:
    image: postgres:latest
    restart: always
    container_name: express_postgres_db_1
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/db
#    volumes:
#      - ./db_postgres:/data/db
    ports:
      - 5432:5432

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    restart: always
    container_name: express_postgres_api_1
    environment:
      - NODE_ENV=dev
      - DB_USER=artemkabanov
      - DB_PASSWORD=HareKrishna108
      - DB_HOST=db
      - DB_DATABASE=nodelogin
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 9000:9000
    links:
      - db
    depends_on:
      - db
